# Generated by Django 2.1.7 on 2019-03-07 15:03

from django.db import migrations
import richtext_poc.model_fields
import richtext_poc.validators
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20180522_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='markdown_body',
            field=richtext_poc.model_fields.MarkdownField(blank=True, validators=[richtext_poc.validators.slug_hyperlinks]),
        ),
        migrations.AddField(
            model_name='homepage',
            name='richtext_body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
