# Generated by Django 2.1.7 on 2019-03-12 20:06

from django.db import migrations
import richtext_poc.model_fields
import richtext_poc.validators
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20190307_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='markdown_body',
            field=richtext_poc.model_fields.MarkdownField(blank=True, help_text='This is help text for a field', validators=[richtext_poc.validators.slug_hyperlinks]),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='richtext_body',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='This is help text for a field'),
        ),
    ]
