# Generated by Django 2.1.7 on 2019-03-18 14:45

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20190312_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='richtext_restricted_body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
