# Generated by Django 2.1.7 on 2019-03-21 08:36

from django.db import migrations
import richtext_poc.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_homepage_richtext_restricted_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='opportunity_list',
            field=wagtail.core.fields.StreamField([('panels', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('body', richtext_poc.blocks.MarkdownBlock())], label='Panel')))], blank=True, verbose_name='Opportunities'),
        ),
    ]
